/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessState"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemResponse"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetApiKeyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddSourceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationProblem"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetTargetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configuration/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigurationProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanState"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilingState"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilingState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilingState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    filter?: string;
                    site?: string;
                    noSite?: boolean;
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewQueueState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    site?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoSearchState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{fileId}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fileId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{fileId}/dismissal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fileId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/dismissals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DismissManyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{fileId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fileId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewDecisionState"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessState: {
            passwordSet: boolean;
            authenticated: boolean;
        };
        AddSourceRequest: {
            path: string;
        };
        AssignRequest: {
            /** Format: uuid */
            videoId: string;
        };
        ConfigurationProblem: {
            message: string;
            configuration: components["schemas"]["ConfigurationState"];
        };
        ConfigurationState: {
            apiKeySet: boolean;
            sources: components["schemas"]["SourceState"][];
            target: null | components["schemas"]["DirectoryState"];
            layout: null | string;
            availableLayouts: components["schemas"]["LayoutOption"][];
            complete: boolean;
            readyToComplete: boolean;
            whatHappensNext: string;
        };
        DirectoryState: {
            path: string;
            usable: boolean;
            problem: null | string;
        };
        DismissManyRequest: {
            fileIds: (number | string)[];
        };
        FiledFileState: {
            /** Format: int32 */
            fileId: number | string;
            name: string;
            state: string;
            scene: null | string;
            targetName: null | string;
            message: null | string;
        };
        FilingState: {
            running: boolean;
            filing: boolean;
            /** Format: date-time */
            plannedAt: null | string;
            /** Format: date-time */
            filedAt: null | string;
            problem: null | string;
            plan: components["schemas"]["PlannedFileState"][];
            /** Format: int32 */
            planTotal: number | string;
            /** Format: int32 */
            wouldFile: number | string;
            whatItWouldDo: null | string;
            results: components["schemas"]["FiledFileState"][];
            /** Format: int32 */
            resultTotal: number | string;
            whatItDid: null | string;
        };
        HealthResponse: {
            status: string;
        };
        IdentificationState: {
            running: boolean;
            /** Format: date-time */
            lastRunFinishedAt: null | string;
            /** Format: int32 */
            lastRunAsked: number | string;
            problem: null | string;
            /** Format: date-time */
            notBefore: null | string;
            /** Format: int32 */
            recognised: number | string;
            /** Format: int32 */
            ambiguous: number | string;
            /** Format: int32 */
            siteOnly: number | string;
            /** Format: int32 */
            unrecognised: number | string;
            /** Format: int32 */
            waiting: number | string;
            /** Format: int32 */
            perceptualBacklog: number | string;
            whatItRecognised: null | string;
        };
        LayoutOption: {
            name: string;
            description: string;
        };
        PlannedFileState: {
            /** Format: int32 */
            fileId: number | string;
            name: string;
            path: string;
            outcome: string;
            scene: null | string;
            quality: null | string;
            directory: null | string;
            targetName: null | string;
            relabelFrom: null | string;
            relabelTo: null | string;
            movement: string;
            moves: boolean;
            message: null | string;
        };
        ProblemResponse: {
            message: string;
        };
        RecognisedState: {
            state: string;
            answer: string;
            because: null | string;
            /** Format: uuid */
            videoId: null | string;
            /** Format: int32 */
            candidates: number | string;
            /** Format: date-time */
            askedAt: string;
        };
        ResolutionState: {
            kind: string;
            from: null | string;
            /** Format: date-time */
            decidedAt: string;
            answer: string;
            /** Format: uuid */
            videoId: null | string;
            title: null | string;
            /** Format: date */
            releaseDate: null | string;
            siteTitle: null | string;
        };
        ReviewCandidateState: {
            /** Format: uuid */
            videoId: string;
            answer: string;
            video: null | components["schemas"]["VideoState"];
        };
        ReviewDecisionState: {
            made: boolean;
            entry: null | components["schemas"]["ReviewEntryState"];
            summary: components["schemas"]["ReviewSummaryState"];
            problem: null | string;
        };
        ReviewEntryState: {
            /** Format: int32 */
            fileId: number | string;
            name: string;
            path: string;
            /** Format: int64 */
            sizeBytes: number | string;
            /** Format: date-time */
            firstSeenAt: string;
            recognised: null | components["schemas"]["RecognisedState"];
            candidates: components["schemas"]["ReviewCandidateState"][];
            decision: null | components["schemas"]["ResolutionState"];
        };
        ReviewQueueState: {
            filter: string;
            /** Format: uuid */
            site: null | string;
            entries: components["schemas"]["ReviewEntryState"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pages: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            total: number | string;
            summary: components["schemas"]["ReviewSummaryState"];
            sites: components["schemas"]["ReviewSiteState"][];
            problem: null | string;
        };
        ReviewSiteState: {
            /** Format: uuid */
            siteId: null | string;
            name: string;
            /** Format: int32 */
            waiting: number | string;
        };
        ReviewSummaryState: {
            /** Format: int32 */
            waiting: number | string;
            /** Format: int32 */
            ambiguous: number | string;
            /** Format: int32 */
            siteOnly: number | string;
            /** Format: int32 */
            unrecognised: number | string;
            /** Format: int32 */
            assigned: number | string;
            /** Format: int32 */
            dismissed: number | string;
            whatIsWaiting: string;
        };
        ScannedFileState: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            sourceId: number | string;
            path: string;
            name: string;
            /** Format: int64 */
            sizeBytes: number | string;
            ready: boolean;
            /** Format: date-time */
            firstSeenAt: string;
            recognised: null | components["schemas"]["RecognisedState"];
        };
        ScannedSourceState: {
            /** Format: int32 */
            sourceId: number | string;
            path: string;
            reachable: boolean;
            problem: null | string;
            /** Format: int32 */
            ready: number | string;
            /** Format: int32 */
            settling: number | string;
            /** Format: int32 */
            total: number | string;
        };
        ScanState: {
            scanning: boolean;
            /** Format: date-time */
            lastScanStartedAt: null | string;
            /** Format: date-time */
            lastScanFinishedAt: null | string;
            problem: null | string;
            onboardingComplete: boolean;
            sources: components["schemas"]["ScannedSourceState"][];
            files: components["schemas"]["ScannedFileState"][];
            /** Format: int32 */
            ready: number | string;
            /** Format: int32 */
            settling: number | string;
            /** Format: int32 */
            total: number | string;
            whatItFound: string;
            identification: components["schemas"]["IdentificationState"];
        };
        SetApiKeyRequest: {
            apiKey: string;
        };
        SetPasswordRequest: {
            password: string;
        };
        SetTargetRequest: {
            path: string;
            layout: string;
        };
        SignInRequest: {
            password: string;
        };
        SourceState: {
            /** Format: int32 */
            id: number | string;
            path: string;
            usable: boolean;
            problem: null | string;
            movement: string;
            movementExplained: string;
        };
        VideoSearchState: {
            answered: boolean;
            videos: components["schemas"]["VideoState"][];
            /** Format: int32 */
            total: number | string;
            problem: null | string;
        };
        VideoState: {
            /** Format: uuid */
            videoId: string;
            answer: string;
            title: null | string;
            /** Format: date */
            releaseDate: null | string;
            /** Format: uuid */
            siteId: null | string;
            siteTitle: null | string;
            performers: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
