// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Ordeno.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Ordeno.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdenoDbContext))]
    [Migration("20260809135557_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.SourceDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("SourceDirectories");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.StoredConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuration", null, t =>
                        {
                            t.HasCheckConstraint("CK_Configuration_SingleRow", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
