// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prdb.Ordeno.Infrastructure.Persistence;

#nullable disable

namespace Prdb.Ordeno.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdenoDbContext))]
    [Migration("20260819152728_OperationLog")]
    partial class OperationLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Access.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.DiscoveredFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerceptualHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PerceptualHashAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PerceptualHashAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerceptualHashState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnchangedSince")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("SourceDirectoryId");

                    b.ToTable("DiscoveredFiles");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.FileIdentification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AskedWithPerceptualHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscoveredFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedBy")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveredFileId")
                        .IsUnique();

                    b.ToTable("FileIdentifications");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.FileResolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscoveredFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveredFileId")
                        .IsUnique();

                    b.ToTable("FileResolutions");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.FiledVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryRoot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityLabel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Directory", "FileName")
                        .IsUnique();

                    b.HasIndex("VideoId", "LibraryRoot");

                    b.ToTable("FiledVideos");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.IdentificationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DescribedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileIdentificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Performers")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileIdentificationId");

                    b.ToTable("IdentificationCandidates", (string)null);
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.OperationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArtworkBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtworkFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtworkPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedBy")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Movement")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityLabel")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("SceneReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneSite")
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SidecarPath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UndoneByRunId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromPath");

                    b.HasIndex("RunId");

                    b.HasIndex("UndoneByRunId");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.OperationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Problem")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("OperationRuns");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.SourceDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("SourceDirectories");
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.StoredConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DownloadArtwork")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaServerApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaServerUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PasswordSetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuration", null, t =>
                        {
                            t.HasCheckConstraint("CK_Configuration_SingleRow", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownloadArtwork = false
                        });
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.DiscoveredFile", b =>
                {
                    b.HasOne("Prdb.Ordeno.Infrastructure.Persistence.SourceDirectory", null)
                        .WithMany()
                        .HasForeignKey("SourceDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.FileIdentification", b =>
                {
                    b.HasOne("Prdb.Ordeno.Infrastructure.Persistence.DiscoveredFile", null)
                        .WithOne()
                        .HasForeignKey("Prdb.Ordeno.Infrastructure.Persistence.FileIdentification", "DiscoveredFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.FileResolution", b =>
                {
                    b.HasOne("Prdb.Ordeno.Infrastructure.Persistence.DiscoveredFile", null)
                        .WithOne()
                        .HasForeignKey("Prdb.Ordeno.Infrastructure.Persistence.FileResolution", "DiscoveredFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.IdentificationCandidate", b =>
                {
                    b.HasOne("Prdb.Ordeno.Infrastructure.Persistence.FileIdentification", null)
                        .WithMany("Candidates")
                        .HasForeignKey("FileIdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.OperationEntry", b =>
                {
                    b.HasOne("Prdb.Ordeno.Infrastructure.Persistence.OperationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prdb.Ordeno.Infrastructure.Persistence.OperationRun", null)
                        .WithMany()
                        .HasForeignKey("UndoneByRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Prdb.Ordeno.Infrastructure.Persistence.FileIdentification", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
